c  -*- Fortran -*-
      write(*,*) "************************            AND             ************************"
      write(*,*) "****                                                                    ****"
      write(*,*) "**** The implementation of this process is discussed in                 ****"
      write(*,*) "****                                                                    ****"
      write(*,*) "**** arXiv:2309.02127, Andrea Banfi, Silvia Ferrario Ravasio, Barbara   ****"
      write(*,*) "**** Jäger, Alexander Karlberg, Felix Reichenbach, Giulia Zanderighi    ****"
      write(*,*) "****                                                                    ****"
      write(*,*) "**** The extension to the polarized case is discussed in                ****"
      write(*,*) "**** arXiv:2404.07702, Ignacio Borsa, Barbara Jäger                     ****"
      write(*,*) "****                                                                    ****"
      write(*,*) "**** and the inclusion of neutrino-induced DIS is presented in          ****"
      write(*,*) "**** 2407.03894, Silvia Ferrario Ravasio, Rhorry Gauld, Barbara  Jäger, ****"
      write(*,*) "**** Alexander Karlberg, Giulia Zanderighi                              ****"
      write(*,*) "****************************************************************************"
